chart-dirs:
  - bitnami
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
debug: true
excluded-charts:
  - common
  - kubeapps
  - kibana
  - kong
  - mariadb-galera
  - discourse
  - ejbca
  - wavefront
  - harbor
  - wavefront-adapter-for-istio
  - wavefront-prometheus-storage-adapter
remote: origin
